using SoapServiceReference; // This connects the code with the SOAP client generated by VS

namespace CustomerCampaign.API.Services;

public class PersonService : IPersonService
{
    public async Task<string> GetPersonNameAsync(string id)
    {
        try
        {
            // Create a client for communicating with the SOAP service
            using var client = new SOAPDemoSoapClient(SOAPDemoSoapClient.EndpointConfiguration.SOAPDemoSoap);

            // Call the method from the external service and pass the customer ID
            var response = await client.FindPersonAsync(id);

            // If the service found the person, return their name
            if (response != null && !string.IsNullOrEmpty(response.Name))
            {
                return response.Name;
            }

            // If the person with that ID does not exist on the server
            return "The customer is not found.";
        }
        catch (Exception ex)
        {
            // In case the external service goes down or there is no internet, the application keeps running
            return $"Error communicating with the SOAP service: {ex.Message}";
        }
    }
}